version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Refit.HttpClientFactory
    versions:
    - 5.2.4
    - 6.0.1
    - 6.0.15
    - 6.0.21
    - 6.0.24
    - 6.0.8
  - dependency-name: refit
    versions:
    - 5.2.4
    - 6.0.1
